name: Quarkus CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and Test
        run: mvn clean verify

      - name: Build Docker Image
        run: docker build -t learn-quarkus .

      - name: Custom Script
        run: |
          echo "Starting build..."
          pwd
          ls -la
          java -version
          mvn --version
          docker --version